version: '2'
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

services:
  postgres:
    build: ./postgres
    image: jh-postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/pg-data:/opt/pg-data
    networks:
      default:
        ipv4_address: 172.28.0.4
  hive:
    build: ./hive
    image: jh-hive
    ports:
      - "10000:10000"
    depends_on:
      - hadoop
    networks:
      default:
        ipv4_address: 172.28.0.3
  hadoop:
    build: ./hadoop
    image: jh-hadoop
    volumes:
      - ./data/hadoop:/opt/hadoop
    ports:
      - "9000:9000" # Hadoop
      - "50070:50070" # HadoopUI Access
    networks:
      default:
        ipv4_address: 172.28.0.5
  rstudio:
    build: ./rstudio
    image: jh-rstudio
    ports:
      - "8787:8787" # RstudioUI
    links:
      - hadoop
      - postgres
    volumes:
      - ./data/rstudio:/home/rstudio
      - ./willtest:/home/rstudio/tests # TEMPORARY directory of test scripts
    depends_on: 
      - hadoop
      - hive
    networks:
      default:
        ipv4_address: 172.28.0.2