version: '2'
services:
  postgres:
    build: ./postgres
    image: jh-postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/pg-data:/opt/pg-data
  hive:
#    build: ./hive
    image: jh-hive
    ports:
      - "10000:10000"
    depends_on:
      - hadoop
  hadoop:
    build: ./hadoop
    image: jh-hadoop
    volumes:
      - ./data/hadoop:/opt/hadoop
    ports:
      - "9000:9000"
      - "50070:50070"
  rstudio:
    build: ./rstudio
    image: jh-rstudio
    ports:
      - "8787:8787"
    links:
      - hadoop
#      - hbase
      - postgres
    volumes:
      - ./data/rstudio:/home/rstudio
    depends_on: 
      - hadoop
      - hive

