/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mlilback' at '8/12/16 1:57 PM' with Gradle 2.8
 *
 * @author mlilback, @date 8/12/16 1:57 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
